dist: trusty
sudo: false
language: node_js
node_js:
  - '7'
env:
  - 'NODE_ENV=integration'
addons:
  postgresql: '9.6'
services:
  - postgresql
before_script:
  - psql -U postgres -c 'create database "lil-erp"'
  - npm run db:up
  - npm run db:seed
script: nyc npm test && nyc report --reporter=text-lcov | coveralls
