dist: trusty
sudo: false
language: node_js
node_js:
  - '7'
  - '10'
env:
  - 'NODE_ENV=integration'
addons:
  postgresql: '9.6'
services:
  - postgresql
before_script:
  - psql -U postgres -c 'create database "lil-erp"'
  - npm run db:cycle
script: npm run cover && npm run check
after_success:
  - bash <(curl -s https://codecov.io/bash)
